### ISSUE TITLE
Support shared libraries

### ISSUE THREAD

**Issue by phretor** [daeh/zotero-obsidian-citations#20]
Are there plans to support reading from multiple BBT or JSON library files? I work on several group libraries (one per project).

**Comment by daeh** [comment]
It makes sense to support group libraries. The only non-trivial thing is to deal zotero items that appear in multiple libraries, since the the plugin currently assumes that a MD file should point is a single zotero item. That constraint exists mostly because it protects against configuration mistakes. I'll think about a user-friendly way to keep the configuration guardrails while also allowing for duplicate zotero items. But in the mean time, I might start by adding an advanced option to relax the constraint so that you can use your group libraries.

**Comment by phretor** [comment]
It does support group library exports already: I can easily export any group library into a bib/json file and link it under the `Citations database path`.

My proposed enhancement is to allow multiple bib/json files, so that users could cite content from multiple bib/json files (i.e., multiple libraries).

Conflicts (i.e., same citation key) could be resolved by keeping the largest or most recent entry.

**Comment by phretor** [comment]
I can use exports from group libraries now. The point is to support multiple of them. Conflicts could be maybe handled by picking the biggest or most up to date one given the same cite key? 😉
